apiVersion: v1
kind: Secret
metadata:
  name: motor-metrics-secrets
  namespace: motor-metrics
type: Opaque
stringData:
  MARKETCHECK_API_KEY: ""  # Set this value when creating the secret
  DATABASE_PASSWORD: ""  # Set this value when creating the secret (should match postgres-secret)

