apiVersion: v1
kind: Secret
metadata:
  name: motor-metrics-secrets
  namespace: motor-metrics
type: Opaque
stringData:
  MARKETCHECK_API_KEY: "KdNXRc9F0R9SrCJahMsP2qNhC5iRqMtk"  # Set this value when creating the secret
  DATABASE_PASSWORD: "changeme"  # Set this value when creating the secret (should match postgres-secret)

