apiVersion: v1
kind: Secret
metadata:
  name: motor-metrics-secrets
  namespace: motor-metrics
type: Opaque
stringData:
  MARKETCHECK_API_KEY: "BMiTlmFL2eVNRosHe5Oq1BYdmGD3QYfF"  # Set this value when creating the secret
  DATABASE_PASSWORD: "changeme"  # Set this value when creating the secret (should match postgres-secret)

